"""Convert Nav2 physical velocity commands to the Jackal Joy interface."""

from geometry_msgs.msg import TwistStamped
import rclpy
from rclpy.node import Node
from sensor_msgs.msg import Joy


class CmdVelToJoy(Node):
    """Bridge stamped Nav2 commands to calibrated, normalized Joy axes."""

    DEFAULT_OUTPUT_FRAME_ID = "cmd_vel_to_joy/generated"
    GENERATED_OUTPUT_MODE_VALUE = 0.0

    def __init__(self):
        super().__init__("cmd_vel_to_joy")

        self.declare_parameter("linear_speed_at_full_axis", 2.0)
        self.declare_parameter("angular_speed_at_full_axis", 0.75)
        self.declare_parameter("cmd_vel_topic", "cmd_vel_smoothed")
        self.declare_parameter("joy_input_topic", "joy")
        self.declare_parameter("joy_output_topic", "joy")
        self.declare_parameter("publish_frequency", 50.0)
        self.declare_parameter("manual_override_axis", 4)
        self.declare_parameter("manual_override_value", -1.0)
        self.declare_parameter(
            "output_frame_id", self.DEFAULT_OUTPUT_FRAME_ID
        )

        self.linear_speed_at_full_axis = float(
            self.get_parameter("linear_speed_at_full_axis").value
        )
        self.angular_speed_at_full_axis = float(
            self.get_parameter("angular_speed_at_full_axis").value
        )
        publish_frequency = float(self.get_parameter("publish_frequency").value)
        self.manual_override_axis = int(
            self.get_parameter("manual_override_axis").value
        )
        self.manual_override_value = float(
            self.get_parameter("manual_override_value").value
        )
        self.output_frame_id = str(
            self.get_parameter("output_frame_id").value
        )

        if self.linear_speed_at_full_axis <= 0.0:
            raise ValueError("linear_speed_at_full_axis must be positive")
        if self.angular_speed_at_full_axis <= 0.0:
            raise ValueError("angular_speed_at_full_axis must be positive")
        if publish_frequency <= 0.0:
            raise ValueError("publish_frequency must be positive")
        if self.manual_override_axis < 0:
            raise ValueError("manual_override_axis cannot be negative")
        if not self.output_frame_id:
            raise ValueError("output_frame_id cannot be empty")

        cmd_vel_topic = str(self.get_parameter("cmd_vel_topic").value)
        joy_input_topic = str(self.get_parameter("joy_input_topic").value)
        joy_output_topic = str(self.get_parameter("joy_output_topic").value)

        # Fail closed during startup until a genuine physical Joy message
        # explicitly selects Auto. A later RC freshness timeout belongs in the
        # long-term single-owner Joy mux.
        self.block_autonomy = True
        self.last_cmd = TwistStamped()

        self.cmd_sub = self.create_subscription(
            TwistStamped, cmd_vel_topic, self.cmd_cb, 20
        )
        self.joy_sub = self.create_subscription(
            Joy, joy_input_topic, self.joy_cb, 20
        )
        self.joy_pub = self.create_publisher(Joy, joy_output_topic, 1)
        self.timer = self.create_timer(1.0 / publish_frequency, self.publish_joy)

        self.get_logger().info(
            "CmdVel to Joy bridge started: "
            f"input={cmd_vel_topic}, output={joy_output_topic}, "
            f"full-scale linear={self.linear_speed_at_full_axis:.2f} m/s, "
            f"angular={self.angular_speed_at_full_axis:.2f} rad/s"
        )
        if joy_input_topic == joy_output_topic:
            self.get_logger().warning(
                "Joy input and output share a topic; generated messages are "
                f"marked with frame_id={self.output_frame_id!r} and ignored "
                "by this bridge. Use separate raw and output Joy topics for "
                "long-term command arbitration."
            )

    @staticmethod
    def clamp(value: float, minimum: float = -1.0, maximum: float = 1.0) -> float:
        return max(min(value, maximum), minimum)

    @classmethod
    def velocity_to_axis(cls, velocity: float, full_axis_speed: float) -> float:
        if full_axis_speed <= 0.0:
            raise ValueError("full_axis_speed must be positive")
        return cls.clamp(velocity / full_axis_speed)

    @staticmethod
    def is_bridge_output(msg: Joy, output_frame_id: str) -> bool:
        """Return whether a Joy message was generated by this bridge."""
        return msg.header.frame_id == output_frame_id

    @staticmethod
    def is_manual_override(
        msg: Joy, manual_override_axis: int, manual_override_value: float
    ) -> bool:
        """Return whether a physical Joy message requests manual control."""
        return (
            len(msg.axes) > manual_override_axis
            and abs(
                msg.axes[manual_override_axis] - manual_override_value
            ) < 1.0e-6
        )

    @staticmethod
    def operator_allows_autonomy(msg: Joy, autonomous_mode_axis: int) -> bool:
        """Match jackal_teleop: only a positive physical mode axis is Auto."""
        return (
            len(msg.axes) > autonomous_mode_axis
            and msg.axes[autonomous_mode_axis] > 0.0
        )

    @classmethod
    def command_axes(
        cls,
        linear_velocity: float,
        angular_velocity: float,
        linear_speed_at_full_axis: float,
        angular_speed_at_full_axis: float,
        mode_axis: int,
    ) -> list[float]:
        """Build axes that jackal_teleop forwards as a velocity command."""
        axes = [0.0] * max(8, mode_axis + 1)
        axes[3] = cls.velocity_to_axis(
            linear_velocity, linear_speed_at_full_axis
        )
        axes[2] = cls.velocity_to_axis(
            angular_velocity, angular_speed_at_full_axis
        )
        # jackal_teleop only publishes its buffered velocity when this axis is
        # non-positive. Physical positive-Auto messages enable this bridge;
        # generated messages then use the original Nav2 value of zero so their
        # velocity reaches /jackal_velocity_controller/cmd_vel.
        axes[mode_axis] = cls.GENERATED_OUTPUT_MODE_VALUE
        return axes

    def joy_cb(self, msg: Joy) -> None:
        if self.is_bridge_output(msg, self.output_frame_id):
            return

        if len(msg.axes) > self.manual_override_axis:
            if self.is_manual_override(
                msg, self.manual_override_axis, self.manual_override_value
            ):
                self.block_autonomy = True
            else:
                self.block_autonomy = not self.operator_allows_autonomy(
                    msg, self.manual_override_axis
                )

    def cmd_cb(self, msg: TwistStamped) -> None:
        self.last_cmd = msg

    def publish_joy(self) -> None:
        if self.block_autonomy:
            return

        joy = Joy()
        joy.header.stamp = self.get_clock().now().to_msg()
        joy.header.frame_id = self.output_frame_id
        joy.axes = self.command_axes(
            self.last_cmd.twist.linear.x,
            self.last_cmd.twist.angular.z,
            self.linear_speed_at_full_axis,
            self.angular_speed_at_full_axis,
            self.manual_override_axis,
        )
        joy.buttons = [0] * 8
        self.joy_pub.publish(joy)


def main(args=None):
    rclpy.init(args=args)
    node = CmdVelToJoy()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()


if __name__ == "__main__":
    main()
